version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout      
      - run:
          gradle test
      - store_test_results:
           path: .    
      - run:
          gradle jar
      - store_test_results:
           path: .
      - store_artifacts:
            path: .
            destination: prefix
